# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtgYxSxdy_7J5Q1TGWeE2H-3D2gwda1D
"""

# -*- coding: utf-8 -*-
import streamlit as st
import joblib
import pandas as pd

# Load model
model = joblib.load("dtc_model.pkl")

# Page config
st.set_page_config(page_title="Wine Type Prediction", page_icon="🍷", layout="centered")

# Custom CSS styling
st.markdown("""
    <style>
        .main {
            background-color: #fdf6f0;
        }
        h1 {
            color: #8B0000;
            text-align: center;
            font-family: 'Georgia', serif;
        }
        .stButton>button {
            background-color: #8B0000;
            color: white;
            border-radius: 10px;
            font-size: 18px;
            padding: 10px 20px;
        }
        .stNumberInput>div>div>input {
            border-radius: 8px;
        }
    </style>
""", unsafe_allow_html=True)

# Title
st.title("🍷 Wine Type Prediction 🍷")
st.markdown("### Enter the wine characteristics below to predict whether it's **Red** or **White**.")

# Inputs in two columns for better layout
col1, col2 = st.columns(2)

with col1:
    fixed_acidity = st.number_input("Fixed Acidity")
    volatile_acidity = st.number_input("Volatile Acidity")
    citric_acid = st.number_input("Citric Acid")
    residual_sugar = st.number_input("Residual Sugar")
    chlorides = st.number_input("Chlorides")
    free_sulfur_dioxide = st.number_input("Free Sulfur Dioxide")

with col2:
    total_sulfur_dioxide = st.number_input("Total Sulfur Dioxide")
    density = st.number_input("Density")
    pH = st.number_input("pH")
    sulphates = st.number_input("Sulphates")
    alcohol = st.number_input("Alcohol")
    quality = st.number_input("Quality", step=1)

# Create DataFrame
input_data = pd.DataFrame([[
    fixed_acidity,
    volatile_acidity,
    citric_acid,
    residual_sugar,
    chlorides,
    free_sulfur_dioxide,
    total_sulfur_dioxide,
    density,
    pH,
    sulphates,
    alcohol,
    quality
]], columns=model.feature_names_in_)

# Prediction button
if st.button("Predict"):
    prediction = model.predict(input_data)[0]
    if prediction == "white":
        st.success("🥂 The wine is **White**")
    else:
        st.error("🍷 The wine is **Red**")